
import './globals.css'
import { Metadata } from 'next'

import Footer from './components/Footer'

export const metadata :Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className='bg-white'>
        
        
        {children}
        <Footer/>
        
        </body>
    </html>
  )
}
